name: DanNitro Collector

on:
  workflow_dispatch:

jobs:
  build:
    name: grabbing stuff ig
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Installing and configuring gen with proxies (you thought this was public huh)
        run: |
            Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/zeontu4hgzbc5npo2j8u9/nitrogencode.txt?rlkey=dqzmorxoriveztqpp3epffwtk&dl=1" -OutFile "nitro.py"
            python -m pip install certifi charset-normalizer idna requests urllib3
            py nitro.py
        env:
             AntiCopyFeature: ${{ secrets.THIS_IS_IN_BETA_SKID }}

      - name: running the collector 🔥🔥
        run: cmd /c Preparation.bat
